Fix flaky test
Test result depended on map iteration order, and hence was
non-deterministic, sample failure:

    --- FAIL: Test_MSKUniqueAppNamesRule (0.00s)
        --- FAIL: Test_MSKUniqueAppNamesRule/reports_duplicate_app_names_across_files (0.00s)
            msk_unique_app_names_test.go:138: Expected issues are not matched:
                   helper.Issues{
                    &{
                            Rule:    &rules.MSKUniqueAppNamesRule{},
                            Message: "'cert_common_name' must be unique across a module, but 'my-names"...,
                            Range: hcl.Range{
                - 			Filename: "second.tf",
                + 			Filename: "first.tf",
                                    Start:    {Line: 4, Column: 3},
                                    End:      {Line: 4, Column: 43},
                            },
                    },
                  }